# Playbook for macOS hosts
# Install packages using Homebrew, implementing ad hoc idempotence
# Assumes that Xcode Command Line Tools are already installed

- hosts: ci-macos
  vars:
    brew_packages:
      - cartr/qt4/qt@4
      - cartr/qt4/qwt-qt4
      - zzuf
      - valgrind
      - cmake
      - node
      - hardlink-osx

  tasks:
    - name: Check for Homebrew
      stat: path=/usr/local/bin/brew
      register: brew_installed

    - name: Install Homebrew
      become_user: ci
      shell: |
        /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
        brew tap cartr/qt4
      when: brew_installed.stat.exists == false

    - name: Check for installed packages
      become_user: ci
      shell: brew list | grep {{ item }}
      register: packages_installed
      with_items: "{{ brew_packages }}"
      ignore_errors: true

    - name: Install packages with Homebrew
      become_user: ci
      shell: brew install {{ item }}
      with_items: "{{ brew_packages }}"
      when: "{{ item not in packages_installed.results|map(attribute='stdout') }}"
