# Playbook for Debian and Ubuntu hosts
# Install packages using Ansible's apt module

- hosts: ci-ubuntu
  tasks:
    - name: Install dependencies
      apt: pkg={{item}} state=installed update_cache=true
      with_items:
        - build-essential
        - cmake
        - devscripts
        - g++
        - gcc
        - git
        - libboost-python-dev
        - libqwt5-qt4
        - libqwt5-qt4-dev
        - libqwt-qt5-dev
        - libudev-dev
        - lintian
        - nodejs
        - qt4-dev-tools
        - qt5-qmake
        - qtbase5-dev
        - qtbase5-dev-tools
        - valgrind

    - name: Update all packages to the latest version
      apt:
        upgrade: dist
